name: steel

dependencies:
  - conda-wrappers
  - python==3.8
  - pybind11==2.4.3
  - pytest==5.3.5
  - cmake==3.16.3
  - sdl2==2.0.10
  - sdl2_gfx==1.0.4
  - sdl2_image==2.0.5
  - sdl2_mixer==2.0.1
  - sdl2_ttf==2.0.15
  

environment:
  PATH:
    - {{ root }}/tools
  PYTHONPATH:
    - {{ root }}/source/python
    - {{ root }}/artifacts-py/libs
  